name = "period-tracker-push"
main = "src/index.js"
compatibility_date = "2024-01-01"

# 매일 오전 8시 KST (= 23:00 UTC)
[triggers]
crons = ["0 23 * * *"]

[[kv_namespaces]]
binding = "SUBSCRIPTIONS"
id = "88993b43f5c34ea4b5831192e94005d7"
